-- Run once in the Supabase project's SQL editor. No signup/auth tables needed.
create table if not exists public.kesher_requests (
  id uuid primary key,
  number bigint generated by default as identity unique,
  title text not null check (char_length(title) between 3 and 160),
  description text not null default '',
  kind text not null check (kind in ('issue','request','idea','improvement')),
  creator_id text not null check (creator_id in ('yitzhak','yosef','daniel','yoel','aviad','web3d')),
  status text not null default 'new' check (status in ('new','in_progress','waiting','done','rejected')),
  due_date date,
  estimate text not null default '',
  revision integer not null default 1 check (revision > 0),
  images jsonb not null default '[]'::jsonb check (jsonb_typeof(images)='array'),
  updates jsonb not null default '[]'::jsonb check (jsonb_typeof(updates)='array'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists kesher_requests_creator_created on public.kesher_requests(creator_id,created_at desc,id desc);
create index if not exists kesher_requests_created on public.kesher_requests(created_at desc,id desc);
alter table public.kesher_requests enable row level security;
revoke all on public.kesher_requests from anon,authenticated;
grant all on public.kesher_requests to service_role;
grant usage,select on sequence public.kesher_requests_number_seq to service_role;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('kesher-photos','kesher-photos',false,900000,array['image/jpeg','image/png','image/webp'])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
